Подготовка шаблона проекта апи
Byndyusoft/byndyusoft-templates-api pull request #2
Opened 2021-06-25 16:58 UTC by Rinatich

2021-06-29 06:51 UTC, litichevskiydv requested changes

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api.Client/Clients/TemplateClient.cs
> +            using var scope = _tracer.BuildSpan(nameof(GetTemplate)).StartActive(true);
Уточни, пожалуйста, зачем мы открываем здесь новый спан? + если это реально нужно делать, то лучше вынести это в базовый класс клиента и не заставлять пользователя писать один и тот же код для каждого из методов.

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api.Client/Clients/HttpServiceClient.cs
> +    public abstract class HttpServiceClient
В классе не хватает заготовки для метода DELETE

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api.Client/Clients/HttpServiceClient.cs
> +        public async Task<string> PostAsync(string url, string content)
Не хватает метода Post, который ничего не возвращает

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api.Client/Interfaces/ITemplateClient.cs
> +        public Task<TemplateDto> GetTemplate(int templateId);
Убери ключевое слово `public` из объявления метода, в интерфейсах оно не используется

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api.Client/Interfaces/ITemplateClient.cs
> +    public interface ITemplateClient
Интерфейс нужно переложить в Byndyusoft.Template.Api.Shared и переназвать в что-то вроде `ITemplateApi`, поскольку это не интерфейс клиента а по сути контракт API

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api.Client/Interfaces/ITemplateClient.cs
> +    public interface ITemplateClient
В идеале наследовать от него и соответсвующий контролер

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api.Client/Utils/HttpQueryParameters.cs
> +    public abstract class HttpQueryParameters
Стоит либо показать на примере зачем этот класс, либо написать по нему документацию

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api.Client/Utils/ServiceCollectionExtensions.cs
> +            services.AddSingleton<ITemplateClient, TemplateClient>();
Уточни, пожалуйста, зачем добавлена это строка и почему нам не достаточно просто зарегать клиент?

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api/Program.cs
> +                           webBuilder.UseSerilog((context, configuration) => configuration
Перенеси, вызов `UseSerilog` на уровень выше до `ConfigureServices`, чтобы он был логером не только для `WebHost`, но и для всего сервиса в целом.
Также добавь  после `.UseDefaultSettings` вызов `UseOpenTracingTraces` чтобы в итоге получилось `.UseDefaultSettings().UseOpenTracingTraces()`

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api/Program.cs
> +            CreateHostBuilder(args).Build().Run();
Давай сделаем чуть более навороченный вариант
```
private static Logger CreateLogger() 
{ 
    var loggerConfiguration = new LoggerConfiguration() 
        .ReadFrom.Configuration(Configuration) 
        .WriteTo.Console(new JsonFormatter()); 

    return loggerConfiguration.CreateLogger(); 
}

using var logger = CreateLogger(); 
try 
{ 
    logger.Information("Starting host"); 
    CreateHostBuilder(args).Build().Run(); 
} 
catch (Exception ex) 
{ 
    logger.Fatal(ex, "Host terminated unexpectedly"); 
    Environment.ExitCode = -1; 
}
```

чтобы не терять ошибки старта сервиса

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api/Properties/launchSettings.json
> +    },
Может дропнем это? Кажется мало кто им пользуется, хотя я могу ошибаться

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api/Startup.cs
> +            if (env.IsDevelopment())
Предлагаю добавлять swagger на всех окружениях кроме прода и изменить условие на `env.IsProduction() == false`

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api/Startup.cs
> +                app.UseDeveloperExceptionPage()
Поясни, пожалуйста, как используется эта страница?

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api/Startup.cs
> +                app.UseDeveloperExceptionPage()
Может ее можно убрать?

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api/Startup.cs
> +            });
Лучше вынести этот кусок в отдельное расширение, чтобы уменьшить объем метода. Тем более что скорее всего эти настойки не будут меняться

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api/Startup.cs
> +            services.AddSwaggerGen();
Также лучше вынести ве связанное со swagger в отдельное расширение

2021-06-29 06:51 UTC, litichevskiydv commented on src/Byndyusoft.Template.Api/Startup.cs
> +            app.UseRouting();
Этот вызов уже есть в пайплайне внизу

2021-07-06 05:52 UTC, kanybekov commented on src/Byndyusoft.Template.Api.Client/Clients/HttpServiceClient.cs
> +    public abstract class HttpServiceClient
+

2021-07-06 05:58 UTC, kanybekov commented on src/Byndyusoft.Template.Api.Client/Clients/HttpServiceClient.cs
> +        public async Task<string> PostAsync(string url, string content)
Удалил метод, который возвращает строку, добавил метод, который ничего не возвращает.

2021-07-06 06:00 UTC, kanybekov commented on src/Byndyusoft.Template.Api.Client/Interfaces/ITemplateClient.cs
> +        public Task<TemplateDto> GetTemplate(int templateId);
+

2021-07-06 06:13 UTC, kanybekov commented on src/Byndyusoft.Template.Api/Startup.cs
> +            app.UseRouting();
+

2021-07-06 06:27 UTC, kanybekov commented on src/Byndyusoft.Template.Api/Startup.cs
> +            });
+

2021-07-06 06:29 UTC, kanybekov commented on src/Byndyusoft.Template.Api/Startup.cs
> +            services.AddSwaggerGen();
+

2021-07-06 06:30 UTC, kanybekov commented on src/Byndyusoft.Template.Api/Startup.cs
> +                app.UseDeveloperExceptionPage()
Не используется, удалил.

2021-07-06 06:31 UTC, kanybekov commented on src/Byndyusoft.Template.Api/Startup.cs
> +            if (env.IsDevelopment())
+

2021-07-06 06:36 UTC, kanybekov commented on src/Byndyusoft.Template.Api.Client/Interfaces/ITemplateClient.cs
> +    public interface ITemplateClient
Чем отличает интерфейс клиента от контракта API?

2021-07-06 06:42 UTC, kanybekov commented on src/Byndyusoft.Template.Api.Client/Clients/TemplateClient.cs
> +            using var scope = _tracer.BuildSpan(nameof(GetTemplate)).StartActive(true);
Если правильно помню, чтобы вызов метода клиента попал в трассу.

2021-07-06 07:09 UTC, Rinatich commented on src/Byndyusoft.Template.Migrator/Program.cs
> +
Нужно в отладке добавить переменную окружения

2021-07-06 07:09 UTC, Rinatich commented on src/Byndyusoft.Template.Migrator/Program.cs
> +
Также нет драйвера Npgsql (нугет пакета). Только в документации нужно описать, что его нужно удалить, если используется MSSQL

2021-07-06 10:03 UTC, kanybekov commented on src/Byndyusoft.Template.Api.Client/Clients/TemplateClient.cs
> +            using var scope = _tracer.BuildSpan(nameof(GetTemplate)).StartActive(true);
Выпилю

2021-07-06 10:17 UTC, kanybekov commented on src/Byndyusoft.Template.Api.Client/Interfaces/ITemplateClient.cs
> +    public interface ITemplateClient
+

2021-07-06 10:18 UTC, kanybekov commented on src/Byndyusoft.Template.Api.Client/Clients/TemplateClient.cs
> +            using var scope = _tracer.BuildSpan(nameof(GetTemplate)).StartActive(true);
+

2021-07-06 10:20 UTC, kanybekov commented on src/Byndyusoft.Template.Migrator/Program.cs
> +
+

2021-07-07 12:16 UTC, litichevskiydv approved these changes

2021-07-08 07:49 UTC, merged