Feature/telemetry
Byndyusoft/byndyusoft-templates-api pull request #26
Opened 2022-08-03 09:03 UTC by Rinatich

2022-08-03 11:01 UTC, litichevskiydv approved these changes

2022-08-04 03:20 UTC, kanybekov commented on templates/src/Api/Infrastructure/OpenTelemetry/ServiceCollectionExtensions.cs
> +            .AddOpenTelemetryTracing
клинап кода делал?

2022-08-04 03:20 UTC, kanybekov commented on templates/src/Api/Infrastructure/OpenTelemetry/TracerProviderBuilderExtensions.cs
> +        var ignoredSegments = new[] { "/swagger", "/favicon", "/healthz", "/metrics" };
возможно, стоит вынести в ридми информацию о том, как отфильтровать запросы из трасс

2022-08-04 03:20 UTC, kanybekov commented on templates/src/Api/Program.cs
> +                                                                            context.Configuration.GetSection("Jaeger").Bind,
почему здесь появилось закладывание на "Jaeger" в файле настроек?

2022-08-04 03:20 UTC, kanybekov commented on templates/src/Api/Startup.cs
> +            services.AddMvcCore().AddTracing();
AddTracing() с новой строки?

2022-08-04 04:25 UTC, Rinatich commented on templates/src/Api/Infrastructure/OpenTelemetry/ServiceCollectionExtensions.cs
> +            .AddOpenTelemetryTracing
клинап в шаблоне опасно делать, удаляет в namespace Byndyusoft.*. Этот код клинап не поменял

2022-08-04 04:27 UTC, Rinatich commented on templates/src/Api/Infrastructure/OpenTelemetry/TracerProviderBuilderExtensions.cs
> +        var ignoredSegments = new[] { "/swagger", "/favicon", "/healthz", "/metrics" };
Создал issue https://github.com/Byndyusoft/byndyusoft-templates-api/issues/27

2022-08-04 04:27 UTC, Rinatich commented on templates/src/Api/Startup.cs
> +            services.AddMvcCore().AddTracing();
Зачем?

2022-08-04 04:28 UTC, Rinatich commented on templates/src/Api/Program.cs
> +                                                                            context.Configuration.GetSection("Jaeger").Bind,
Настройки будут браться из секции с названием Jaeger

2022-08-04 04:37 UTC, kanybekov commented on templates/src/Api/Program.cs
> +                                                                            context.Configuration.GetSection("Jaeger").Bind,
Стоит добавить описание настроек в ридми

2022-08-04 04:40 UTC, kanybekov requested changes

2022-08-04 04:40 UTC, kanybekov commented on templates/src/Api/Startup.cs
> +            services.AddMvcCore().AddTracing();
если несколько блоков, каждый с новой строки делать

2022-08-04 04:40 UTC, Rinatich commented on templates/src/Api/Startup.cs
> +            services.AddMvcCore().AddTracing();
++

2022-08-04 04:42 UTC, Rinatich commented on templates/src/Api/Program.cs
> +                                                                            context.Configuration.GetSection("Jaeger").Bind,
https://github.com/Byndyusoft/byndyusoft-templates-api/issues/28

2022-08-04 04:43 UTC, kanybekov approved these changes

2022-08-04 04:44 UTC, merged