Создал шаблон проекта
Byndyusoft/byndyusoft-templates-api pull request #3
Opened 2021-07-08 08:05 UTC by Rinatich

2021-07-08 08:15 UTC, kanybekov requested changes

2021-07-08 08:15 UTC, kanybekov commented on github/workflows/pull-request.yml
> +      - name: test
тест не нужен?

2021-07-08 08:15 UTC, kanybekov commented on github/workflows/release.yml
> +      - name: test
тест не нужен?

2021-07-08 08:16 UTC, kanybekov approved these changes

2021-07-09 11:46 UTC, litichevskiydv approved these changes

2021-07-09 11:49 UTC, merged