Поменял название шаблона на конвенцию, которую используют Microsoft при выкатке шаблонов
Byndyusoft/byndyusoft-templates-api pull request #33
Opened 2023-06-01 11:00 UTC by Alex-Grigorichev

Например:
Microsoft.DotNet.Web.ProjectTemplates.5.0
Microsoft.DotNet.Common.ProjectTemplates.5.0
Microsoft.Azure.WebJobs.ProjectTemplates

2023-06-14 12:22 UTC, Mblkolo approved these changes

2023-06-22 09:58 UTC, Rinatich requested changes

2023-06-22 09:58 UTC, Rinatich commented on Byndyusoft.DotNet.Web.ProjectTemplate.csproj
> +		<Description>Byndyusoft Web API</Description>
давай Byndyusoft Web API template. Это же шаблон в нугет-пакете. Что думаешь?

2023-06-22 09:58 UTC, Rinatich commented on templates/.template.config/template.json
> +   "name":"Byndyusoft Web API",
давай Byndyusoft Web API template. Это же шаблон в нугет-пакете. Что думаешь?

2023-06-22 09:58 UTC, Rinatich commented on templates/README.md
>  ASP.NET Core MVC tracing.
Тестировал, замена на новое имя нормально работает, все билдится?

2023-06-23 04:42 UTC, Alex-Grigorichev commented on templates/README.md
>  ASP.NET Core MVC tracing.
Да

2023-06-23 04:43 UTC, Alex-Grigorichev commented on Byndyusoft.DotNet.Web.ProjectTemplate.csproj
> +		<Description>Byndyusoft Web API</Description>
++

2023-06-23 04:44 UTC, Alex-Grigorichev commented on templates/.template.config/template.json
> +   "name":"Byndyusoft Web API",
++

2023-06-26 05:40 UTC, Rinatich approved these changes

2023-06-29 07:50 UTC, merged