Удалил ASP.NET Core MVC tracing, добавил блок с коротким названием сервиса
Byndyusoft/byndyusoft-templates-api pull request #44
Opened 2023-07-03 08:27 UTC by Alex-Grigorichev

2023-07-03 10:20 UTC, Rinatich requested changes

2023-07-03 10:20 UTC, Rinatich commented on templates/README.md
> +- Anything important to you...
To service potential consumers

2023-07-03 10:20 UTC, Rinatich commented on templates/README.md
> +- API main functional. (For example: Provides easiest way to store and share pictures)
functionality? functions?

2023-07-03 11:29 UTC, Alex-Grigorichev commented on templates/README.md
> +- API main functional. (For example: Provides easiest way to store and share pictures)
functions

2023-07-03 11:34 UTC, Alex-Grigorichev commented on templates/README.md
> +- Anything important to you...
++

2023-07-04 06:52 UTC, Rinatich approved these changes

2023-07-04 06:53 UTC, merged