Обновил версии пакетов OpenTelemetry до более актуальных версий.
Byndyusoft/byndyusoft-templates-api pull request #47
Opened 2023-07-18 10:28 UTC by Alex-Grigorichev

- Обновил версии пакетов OpenTelemetry до более актуальных версий.
- Поправил появившиеся ошибки.

2023-07-18 11:22 UTC, Rinatich requested changes

2023-07-18 11:22 UTC, Rinatich commented on templates/src/Api/Api.csproj
> +		<PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.5.0-rc.1" />
есть не rc?

2023-07-18 11:22 UTC, Rinatich commented on templates/src/Api/Api.csproj
> +		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.0-beta.1" />
убирай беты, из-за них часто не работает код

2023-07-18 11:28 UTC, Alex-Grigorichev commented on templates/src/Api/Api.csproj
> +		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.0-beta.1" />
Тут либо бета, либо довольно старый rc.

2023-07-18 11:29 UTC, Alex-Grigorichev commented on templates/src/Api/Api.csproj
> +		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.0-beta.1" />
Выглядит, будто разработчики OpenTelemetry не умеют делать нормальное версионирование...

2023-07-18 11:30 UTC, Rinatich commented on templates/src/Api/Api.csproj
> +		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.0-beta.1" />
я пробовал обновить, с бетой все плохо, не работает, убирай

2023-07-18 11:34 UTC, Alex-Grigorichev commented on templates/src/Api/Api.csproj
> +		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.5.0-beta.1" />
убрал

2023-07-18 11:35 UTC, Rinatich approved these changes

2023-07-24 06:01 UTC, litichevskiydv approved these changes

2023-07-24 06:03 UTC, merged