Заменил использование OpenTelemetry.Exporter.Jaeger на OpenTelemetry.Exporter.OpenTelemetryProtocol
Byndyusoft/byndyusoft-templates-api pull request #50
Opened 2023-09-05 13:22 UTC by Alex-Grigorichev

2023-09-18 09:31 UTC, Rinatich approved these changes

2023-09-18 09:32 UTC, Rinatich requested changes

2023-09-18 09:32 UTC, Rinatich commented on Byndyusoft.DotNet.Web.ProjectTemplate.csproj
> +		<PackageVersion>1.3.8</PackageVersion>
мне кажется, обратной совместимости нет ) надо мажорную версию менять

2023-09-20 05:09 UTC, Alex-Grigorichev commented on Byndyusoft.DotNet.Web.ProjectTemplate.csproj
> +		<PackageVersion>1.3.8</PackageVersion>
Не совсем понятно, какая может быть совместимость в шаблонах сервисов.
Хочу обсудить по каким правилам мы версионируем шаблоны и описать эти правила в ридми, как тебе?

2023-09-21 05:39 UTC, Alex-Grigorichev commented on Byndyusoft.DotNet.Web.ProjectTemplate.csproj
> +		<PackageVersion>1.3.8</PackageVersion>
++

2023-09-21 05:44 UTC, Rinatich approved these changes

2023-09-21 05:45 UTC, merged