Обновлена версия до .NET 8
Byndyusoft/byndyusoft-templates-api pull request #57
Opened 2024-02-29 10:22 UTC by jva44ka

2024-02-29 12:13 UTC, Rinatich approved these changes

2024-12-03 12:39 UTC, litichevskiydv requested changes

2024-12-03 12:39 UTC, litichevskiydv commented on templates/src/Api/Startup.cs
>      public class Startup
Изучи подход, описанный в [статье](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-8.0), возможно, нам стоит на него перейти

2024-12-04 14:30 UTC, litichevskiydv requested changes

2024-12-05 19:03 UTC, litichevskiydv requested changes

2024-12-05 19:03 UTC, litichevskiydv commented on templates/src/Api/Extensions/ServicesCollectionExtensions.cs
> +                .AddJsonOptions(options =>
Перенести `options =>` на новую строчку и отформатировать

2024-12-05 19:03 UTC, litichevskiydv commented on templates/src/Api/Extensions/ServicesCollectionExtensions.cs
> +                    options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));
Перенести `);` на новую строчку и отформатировать

2024-12-05 19:03 UTC, litichevskiydv commented on templates/src/Api/Infrastructure/OpenTelemetry/ServiceCollectionExtensions.cs
>              .WithTracing
Поставить `(` после `.WithTracing` и отформатировать

2024-12-10 07:08 UTC, merged